'use strict';
const KEY='him-chapter-3';
const oldKeys=['him-chapter-2','him-chapter-1','homeInMotionV01'];
const dayThemes={0:['Sunday','Be'],1:['Monday','Refill'],2:['Tuesday','Flow'],3:['Wednesday','Explore'],4:['Thursday','Create'],5:['Friday','Celebrate'],6:['Saturday','Home']};
const chapterMeta=[['rise','Rise','☀'],['family','Family Launch','⌂'],['momentum','Momentum','↟'],['adventure','Adventure','✦'],['restore','Restore','♡'],['gather','Gather','◡'],['rest','Rest','☾']];
const $=id=>document.getElementById(id);
const iso=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const uid=()=>globalThis.crypto?.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const nextDay=n=>{const d=new Date();d.setDate(d.getDate()+((n-d.getDay()+7)%7));return iso(d)};
const list=s=>s.split('\n').map(x=>x.trim()).filter(Boolean).map(text=>({id:uid(),text,done:false}));
const starter={entered:false,openChapter:'rise',declaration:'The Ciones are brave.',intention:'Protect the momentum.',nudge:'That Walmart return has been patiently waiting. Since you’re already out, today could be its day.',chapters:{rise:list('Breakfast\nGet dressed'),family:list('Kids breakfast\nKids get ready'),momentum:list('Gym'),adventure:list('Library after the gym'),restore:list('Quiet hour\nQuick reset'),gather:list('Baked ziti\nFamily walk'),rest:list('Baths\nBedtime\nClose the kitchen')},thoughts:[{id:uid(),text:'Find one cute wine glass',created:Date.now()-86400000*5,photo:null},{id:uid(),text:'Book family photos',created:Date.now()-86400000*2,photo:null}],collections:{Errands:['Buy one wine glass'],Family:['Book family photos'],Home:[],Kids:[],Someday:[]},events:[{id:uid(),title:'Swim lessons',date:nextDay(2),time:'11:30',calendar:'Rosie'},{id:uid(),title:'Gym field day',date:nextDay(5),time:'10:30',calendar:'Family'},{id:uid(),title:'Library',date:iso(new Date()),time:'12:30',calendar:'Family'}]};
function normalize(raw){if(!raw)return structuredClone(starter);const s={...structuredClone(starter),...raw};s.chapters=s.chapters||{};chapterMeta.forEach(([k])=>{const v=s.chapters[k];if(Array.isArray(v)){s.chapters[k]=v.map(i=>typeof i==='string'?{id:uid(),text:i,done:false}:{id:i.id||uid(),text:i.text||'',done:!!i.done}).filter(i=>i.text)}else if(typeof v==='string'){s.chapters[k]=list(v)}else{s.chapters[k]=[]}});s.thoughts=(s.thoughts||[]).map(t=>({...t,id:t.id||uid(),created:t.created||Date.now(),photo:t.photo||null}));s.collections=s.collections||structuredClone(starter.collections);s.events=s.events||[];return s}
function load(){let raw=localStorage.getItem(KEY);if(!raw){for(const k of oldKeys){if(localStorage.getItem(k)){raw=localStorage.getItem(k);break}}}try{return normalize(raw?JSON.parse(raw):null)}catch{return structuredClone(starter)}}
let state=load();
function persist(){localStorage.setItem(KEY,JSON.stringify(state))}
function saveAndRender(){persist();renderAll()}
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
if(state.entered){$('cover').classList.add('hidden');$('app').classList.remove('hidden')}
$('enterApp').addEventListener('click',()=>{state.entered=true;persist();$('cover').classList.add('hidden');$('app').classList.remove('hidden')});
function go(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.nav)));
function greetingForHour(h){if(h>=5&&h<12)return'Good morning';if(h>=12&&h<17)return'Good afternoon';if(h>=17&&h<20)return'Good evening';return'Good night'}
function renderHeader(){const n=new Date();$('todayDate').textContent=n.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});$('greeting').textContent=`${greetingForHour(n.getHours())}, Lola.`;const[d,t]=dayThemes[n.getDay()];$('themeLine').textContent=`${d} · ${t}`}
function renderTimeline(){const wrap=$('timeline');wrap.innerHTML='';chapterMeta.forEach(([key,name,icon])=>{const items=state.chapters[key]||[];const open=state.openChapter===key;const article=document.createElement('article');article.className=`chapter-item${open?' open':''}`;article.innerHTML=`<div class="chapter-dot">${icon}</div><div class="chapter-card"><div class="chapter-head"><h3>${name}</h3><button type="button" class="chapter-toggle" data-toggle="${key}" aria-expanded="${open}">${open?'−':'+'}</button></div><div class="chapter-content"><div class="checklist">${items.length?items.map(i=>`<label class="check-row${i.done?' done':''}"><input type="checkbox" data-check-chapter="${key}" data-check-id="${i.id}" ${i.done?'checked':''}><span>${esc(i.text)}</span></label>`).join(''):'<p class="empty-chapter">Nothing planned here—and that is completely allowed.</p>'}</div><div class="chapter-add-row"><textarea rows="1" data-add-input="${key}" placeholder="Add one item per line"></textarea><button type="button" class="pill-btn" data-add-items="${key}">Add</button></div></div></div>`;wrap.appendChild(article)});
 wrap.querySelectorAll('[data-toggle]').forEach(b=>b.addEventListener('click',()=>{state.openChapter=state.openChapter===b.dataset.toggle?null:b.dataset.toggle;saveAndRender()}));
 wrap.querySelectorAll('[data-check-chapter]').forEach(c=>c.addEventListener('change',()=>{const item=state.chapters[c.dataset.checkChapter].find(x=>x.id===c.dataset.checkId);if(item)item.done=c.checked;persist();renderTimeline();toast(c.checked?'Little win noted.':'Back in motion.',c.checked)}));
 wrap.querySelectorAll('[data-add-items]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.addItems;const input=wrap.querySelector(`[data-add-input="${key}"]`);const additions=list(input.value);if(!additions.length)return toast('Add a line first.');state.chapters[key].push(...additions);input.value='';persist();renderTimeline();toast('Chapter updated.',true)}));
}
function renderStory(){$('nudgeText').textContent=state.nudge}
let calDate=new Date();
function renderMonth(){const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0);let h=`<div class="month-head"><button id="prev" class="icon-btn">‹</button><h3>${first.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h3><button id="next" class="icon-btn">›</button></div><div class="month-grid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="weekday">${x}</div>`).join('')}`;for(let i=0;i<first.getDay();i++)h+='<div></div>';for(let d=1;d<=last.getDate();d++){const date=iso(new Date(y,m,d)),ev=state.events.filter(e=>e.date===date).slice(0,3);h+=`<div class="day ${date===iso(new Date())?'today':''}" data-date="${date}"><b>${d}</b>${ev.map(e=>`<div class="event ${esc(e.calendar)}">${esc(e.title)}</div>`).join('')}</div>`}h+='</div>';$('monthView').innerHTML=h;$('prev').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderMonth()};$('next').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderMonth()};document.querySelectorAll('.day').forEach(x=>x.addEventListener('click',()=>openEvent(x.dataset.date)))}
function startWeek(d){const x=new Date(d);x.setDate(x.getDate()-x.getDay());x.setHours(0,0,0,0);return x}
function renderWeek(){const s=startWeek(new Date());let h=`<div class="week-header"><span>This Week’s Declaration</span><h3>${esc(state.declaration)}</h3><p>${esc(state.intention)}</p></div><div class="week-grid">`;for(let i=0;i<7;i++){const d=new Date(s);d.setDate(s.getDate()+i);const date=iso(d),[day,theme]=dayThemes[d.getDay()],ev=state.events.filter(e=>e.date===date);h+=`<article class="week-card ${date===iso(new Date())?'today':''}"><div class="week-top"><div><span>${day}</span><h3>${theme}</h3></div><b>${d.getDate()}</b></div><div class="week-events">${ev.length?ev.map(e=>`<span class="event ${esc(e.calendar)}">${e.time?esc(e.time)+' · ':''}${esc(e.title)}</span>`).join(''):'<span class="meta">Some breathing room.</span>'}</div></article>`}h+='</div><article class="card" style="margin-top:14px"><span>One Thing Worth Celebrating</span><h3>What felt good this week?</h3></article>';$('weekView').innerHTML=h}
function age(ts){const d=Math.floor((Date.now()-ts)/86400000);return d===0?'Captured today':d===1?'Captured yesterday':`Waiting ${d} days`}
function renderInbox(){const listEl=$('inboxList');listEl.innerHTML=state.thoughts.length?'':'<article class="card"><p>Your inbox is quiet. Anything you capture will wait safely here.</p></article>';state.thoughts.forEach(t=>{const a=document.createElement('article');a.className='thought';a.innerHTML=`<div class="thought-main">${t.photo?`<img src="${t.photo}" alt="Captured photo">`:''}<div><p>${esc(t.text)}</p><span class="meta">${age(t.created)}</span></div></div><button type="button" class="pill-btn sort" data-id="${t.id}">Sort</button>`;listEl.appendChild(a)});listEl.querySelectorAll('.sort').forEach(b=>b.addEventListener('click',()=>openSort(b.dataset.id)))}
function renderCollections(){const grid=$('collectionGrid');grid.innerHTML='';Object.entries(state.collections).forEach(([name,items])=>{const c=document.createElement('article');c.className='collection';c.innerHTML=`<h3>${esc(name)}</h3>${items.length?`<ul>${items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`:'<p>Nothing here yet.</p>'}<button type="button" class="secondary collection-add" data-collection="${esc(name)}">+ Add here</button>`;grid.appendChild(c)});grid.querySelectorAll('.collection-add').forEach(b=>b.addEventListener('click',()=>{const text=prompt(`Add something to ${b.dataset.collection}`);if(text?.trim()){state.collections[b.dataset.collection].push(text.trim());saveAndRender();toast('Found a home.',true)}}));const options=Object.keys(state.collections).map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');$('collectionSelect').innerHTML=options;$('captureCollectionSelect').innerHTML=options}
function renderAuthor(){$('declaration').value=state.declaration;$('intention').value=state.intention;$('authorChapterEditors').innerHTML=chapterMeta.map(([key,name])=>`<label class="author-chapter">${name}<textarea data-author-chapter="${key}" placeholder="One item per line">${esc((state.chapters[key]||[]).map(i=>i.text).join('\n'))}</textarea></label>`).join('');$('thoughtCount').textContent=state.thoughts.length;$('authorInbox').innerHTML=state.thoughts.slice(0,5).map(t=>`<div class="author-thought"><span>${esc(t.text)}</span><button type="button" class="pill-btn author-sort" data-id="${t.id}">Find a home</button></div>`).join('');document.querySelectorAll('.author-sort').forEach(b=>b.addEventListener('click',()=>openSort(b.dataset.id)))}
function renderAll(){renderHeader();renderTimeline();renderStory();renderMonth();renderWeek();renderInbox();renderCollections();renderAuthor()}
document.querySelectorAll('[data-cal]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-cal]').forEach(x=>x.classList.toggle('active',x===b));$('monthView').classList.toggle('active',b.dataset.cal==='month');$('weekView').classList.toggle('active',b.dataset.cal==='week')}));
document.querySelectorAll('[data-cap]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-cap]').forEach(x=>x.classList.toggle('active',x===b));$('captureInbox').classList.toggle('active',b.dataset.cap==='inbox');$('captureCollections').classList.toggle('active',b.dataset.cap==='collections')}));
let selectedPhoto=null,pendingCapture=null,pendingThought=null;
const fileURL=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});
$('photoInput').addEventListener('change',async()=>{const f=$('photoInput').files?.[0];if(!f)return;try{selectedPhoto=await fileURL(f);$('photoPreview').src=selectedPhoto;$('photoPreview').classList.remove('hidden')}catch{toast('That photo could not be loaded.')}});
$('captureBtn').addEventListener('click',()=>{const text=$('captureInput').value.trim();if(!text&&!selectedPhoto)return toast('Give me a thought or photo to capture.');pendingCapture={id:uid(),text:text||'Photo captured',created:Date.now(),photo:selectedPhoto};$('captureInput').value='';$('photoInput').value='';$('photoPreview').src='';$('photoPreview').classList.add('hidden');selectedPhoto=null;renderCollections();$('captureHomeDialog').showModal();toast('Thought captured.',true)});
document.querySelectorAll('[data-capture-home]').forEach(b=>b.addEventListener('click',()=>{if(!pendingCapture)return;const dest=b.dataset.captureHome;if(dest==='inbox'){state.thoughts.unshift(pendingCapture);finishCapture('Safe in your Inbox.')}else if(dest==='collection'){state.collections[$('captureCollectionSelect').value].push(pendingCapture.text);finishCapture('Found a home.',true)}else if(dest==='calendar'){$('captureHomeDialog').close();openEvent();$('eventTitle').value=pendingCapture.text;pendingCapture=null;toast('Ready for a date.')}else{pendingThought=pendingCapture;$('captureHomeDialog').close();pendingCapture=null;openChapterPicker()}}));
function finishCapture(message,spark=false){pendingCapture=null;$('captureHomeDialog').close();saveAndRender();toast(message,spark)}
$('voiceCapture').addEventListener('click',()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const r=new SR();r.lang='en-US';r.interimResults=false;r.onresult=e=>{$('captureInput').value=e.results[0][0].transcript;toast('Voice thought ready to capture.')};r.onerror=()=>voiceFallback();r.start();toast('Listening…')}else voiceFallback()});
function voiceFallback(){go('capture');$('captureInput').focus();toast('Tap the microphone on your iPhone keyboard to dictate.')}
function openEvent(date=iso(new Date())){$('eventDate').value=date;$('eventDialog').showModal()}
$('newEvent').addEventListener('click',()=>openEvent());
$('eventForm').addEventListener('submit',e=>{e.preventDefault();const title=$('eventTitle').value.trim();if(!title)return;state.events.push({id:uid(),title,date:$('eventDate').value,time:$('eventTime').value,calendar:$('eventCalendar').value});$('eventForm').reset();$('eventDialog').close();saveAndRender();toast('Event added.',true)});
function openSort(id){const t=state.thoughts.find(x=>x.id===id);if(!t)return;$('sortId').value=id;$('sortTitle').textContent=t.text;renderCollections();$('sortDialog').showModal()}
document.querySelectorAll('[data-dest]').forEach(b=>b.addEventListener('click',()=>{const id=$('sortId').value,t=state.thoughts.find(x=>x.id===id);if(!t)return;const d=b.dataset.dest;if(d==='story'){pendingThought=t;$('sortDialog').close();openChapterPicker()}else if(d==='calendar'){$('sortDialog').close();openEvent();$('eventTitle').value=t.text;removeThought(id);persist();renderAll();toast('Ready for a date.')}else if(d==='collection'){state.collections[$('collectionSelect').value].push(t.text);removeThought(id);$('sortDialog').close();saveAndRender();toast('Found a home.',true)}else{removeThought(id);$('sortDialog').close();saveAndRender();toast('Thought released.')}}));
function openChapterPicker(){$('chapterChoices').innerHTML=chapterMeta.map(([k,n])=>`<button type="button" class="destination" data-pick="${k}">${n}</button>`).join('');$('chapterChoices').querySelectorAll('[data-pick]').forEach(b=>b.addEventListener('click',()=>{if(!pendingThought)return;state.chapters[b.dataset.pick].push({id:uid(),text:pendingThought.text,done:false});removeThought(pendingThought.id);pendingThought=null;$('chapterDialog').close();saveAndRender();toast('Added to today’s story.',true)}));$('chapterDialog').showModal()}
function removeThought(id){state.thoughts=state.thoughts.filter(x=>x.id!==id)}
$('addCollection').addEventListener('click',()=>{const n=prompt('What should this collection be called?')?.trim();if(!n)return;if(state.collections[n])return toast('That collection already exists.');state.collections[n]=[];saveAndRender();toast('Collection created.',true)});
$('authorForm').addEventListener('submit',e=>{e.preventDefault();state.declaration=$('declaration').value.trim()||state.declaration;state.intention=$('intention').value.trim()||state.intention;document.querySelectorAll('[data-author-chapter]').forEach(area=>{const oldDone=new Map((state.chapters[area.dataset.authorChapter]||[]).map(i=>[i.text,i.done]));state.chapters[area.dataset.authorChapter]=area.value.split('\n').map(x=>x.trim()).filter(Boolean).map(text=>({id:uid(),text,done:oldDone.get(text)||false}))});saveAndRender();toast('Tomorrow’s story is written.',true);go('story')});
function toast(msg,spark=false){const el=$('toast');el.textContent=msg;el.classList.add('show');if(spark)sparkle();clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2100)}
function sparkle(){for(let i=0;i<9;i++){const s=document.createElement('span');s.className='spark';s.textContent=['✦','⋆','✧','★'][i%4];s.style.left=(42+Math.random()*16)+'%';s.style.top=(60+Math.random()*12)+'%';s.style.color=['#d5b36c','#819379','#d9a99f'][i%3];$('sparkles').appendChild(s);setTimeout(()=>s.remove(),900)}}
$('closeStory').addEventListener('click',()=>{$('closeOverlay').classList.remove('hidden');sparkle()});
$('notYet').addEventListener('click',()=>$('closeOverlay').classList.add('hidden'));
$('finishClosing').addEventListener('click',()=>{$('closeOverlay').classList.add('hidden');toast('Good night, Lola.',true)});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
$('resetDemo').addEventListener('click',()=>{if(confirm('Reset Home in Motion to the original demo?')){localStorage.removeItem(KEY);oldKeys.forEach(k=>localStorage.removeItem(k));state=structuredClone(starter);saveAndRender();toast('Fresh pages, ready to write.',true)}});
if('serviceWorker'in navigator){window.addEventListener('load',async()=>{try{const regs=await navigator.serviceWorker.getRegistrations();for(const reg of regs)await reg.unregister();const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)));await navigator.serviceWorker.register('service-worker.js?v=3')}catch{}})}
renderAll();
